server:
  port: 8091
logging:
    level:
        org.springframework: info
        data: DEBUG
        security: DEBUG
    config: classpath:logback-spring.xml
spring:
  mvc:
    static-path-pattern: /**
  thymeleaf:
    servlet:
      content-type: text/html
    encoding: UTF-8
    cache: false
  datasource:
         type: com.alibaba.druid.pool.DruidDataSource
         url: jdbc:mysql://www.xd999.online:3306/super_blog_db?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC&useSSL=false
         username: root
         password: root1998
         driver-class-name: com.mysql.jdbc.Driver
mybatis:
  typeAliasesPackage: org.edu.cdtu.bbxx.model.domain
  mapperLocations: classpath:mapper/*/*.xml
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql